// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalPortal.Infra.Db;

#nullable disable

namespace UniversalPortal.Infra.Migrations.MasterTenantDb
{
    [DbContext(typeof(MasterTenantDbContext))]
    [Migration("20260721041508_MasterTenantDB")]
    partial class MasterTenantDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversalPortal.Application.MasterTenant.Entities.MasterTenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenantId");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenant_Code");

                    b.HasIndex("TenantName")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenant_Name");

                    b.ToTable("DbSet");
                });
#pragma warning restore 612, 618
        }
    }
}
